name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Prepare Gradle Wrapper (self-heal)
        shell: bash
        run: |
          set -e
          chmod +x gradlew || true
          if ! ./gradlew --version >/dev/null 2>&1; then
            echo "Gradle wrapper is broken. Repairing..."
            curl -sSL -o gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q gradle-8.7-bin.zip
            ./gradle-8.7/bin/gradle wrapper --gradle-version 8.7
            rm -f gradle-8.7-bin.zip
          fi

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./

      - name: Build Debug APK
        working-directory: ./
        shell: bash
        run: |
          set -e
          chmod +x gradlew
          ./gradlew --version
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
